//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTMLreader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HTMLreader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///	&lt;title&gt;Document&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;div&gt;
        ///		&lt;a href=&quot;simplePage_1.html&quot;&gt;&lt;h1&gt;раздел 1&lt;/h1&gt;&lt;/a&gt;
        ///		&lt;p&gt;
        ///			--раздел--1
        ///			краткое описание
        ///			краткое описание
        ///		&lt;/p&gt;
        ///	&lt;/div&gt;
        ///	&lt;div&gt;
        ///		&lt;a href=&quot;simplePage_2.html&quot;&gt;&lt;h1&gt;раздел 2&lt;/h1&gt;&lt;/a&gt;
        ///		&lt;p&gt;
        ///			--раздел--2
        ///			краткое описание
        ///			краткое описание
        ///		&lt;/p&gt;
        ///	&lt;/div&gt;
        ///
        ///	&lt;div&gt;
        ///		&lt;a href=&quot;simplePage_3.html&quot;&gt;&lt;h1&gt;раздел 3.1&lt;/h1&gt;&lt;/a&gt;
        ///		&lt;a href=&quot;simplePage_4.html&quot;&gt;&lt;h1&gt;раздел 3.2&lt;/h1&gt;&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mainPage {
            get {
                return ResourceManager.GetString("mainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///	&lt;title&gt;Document&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;div&gt;
        ///		&lt;h1&gt;
        ///			Простая страница 1.
        ///		&lt;/h1&gt;
        ///		&lt;p&gt;
        ///			
        ///			----------1---------------
        ///			какойто текст на странице 1
        ///		&lt;/p&gt;
        ///	&lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string simplePage_1 {
            get {
                return ResourceManager.GetString("simplePage_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///	&lt;title&gt;Document&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;div&gt;
        ///		&lt;h1&gt;
        ///			Простая страница 2.
        ///		&lt;/h1&gt;
        ///		&lt;p&gt;
        ///			
        ///			----------2---------------
        ///			какойто текст на странице 2
        ///		&lt;/p&gt;
        ///	&lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string simplePage_2 {
            get {
                return ResourceManager.GetString("simplePage_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///	&lt;title&gt;Document&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;div&gt;
        ///		&lt;h1&gt;
        ///			Простая страница 3.
        ///		&lt;/h1&gt;
        ///		&lt;p&gt;
        ///			----------3---------------
        ///			какойто текст на странице 3
        ///		&lt;/p&gt;
        ///	&lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string simplePage_3 {
            get {
                return ResourceManager.GetString("simplePage_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///	&lt;title&gt;Document&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;div&gt;
        ///		&lt;h1&gt;
        ///			Простая страница 4.
        ///		&lt;/h1&gt;
        ///		&lt;p&gt;
        ///			----------4---------------
        ///			какойто текст на странице 4 
        ///
        ///		&lt;/p&gt;
        ///	&lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string simplePage_4 {
            get {
                return ResourceManager.GetString("simplePage_4", resourceCulture);
            }
        }
    }
}
